import { kabobToCamelCaseReducer } from './utils.js';

export const properties = [
  'position',
  'top',
  'right',
  'bottom',
  'left',
  'float',
  'margin-top',
  'margin-right',
  'margin-bottom',
  'margin-left',
  'margin',
  'width',
  'min-width',
  'max-width',
  'height',
  'min-height',
  'max-height',
  'flex-basis',
  '-ms-flex-preferred-size',
  'flex-grow',
  '-ms-flex-positive',
  'flex-shrink',
  '-ms-flex-negative',
  'flex',
  '-webkit-box-flex',
  '-ms-flex',
  'align-self',
  '-ms-grid-row-align, -ms-flex-item-align',
  'order',
  '-ms-flex-order',
  'grid-column-start',
  '-ms-grid-column',
  'grid-column-end',
  '-ms-grid-column-span',
  'grid-column',
  'grid-row-end',
  '-ms-grid-row-span',
  'grid-row-start',
  '-ms-grid-row',
  'grid-row',
  'grid-area',
  'justify-self',
  '-ms-grid-column-align',
  'place-self',
  'visibility',
];

export const propertiesCamel = properties.reduce(kabobToCamelCaseReducer, []);
